### PR TITLE
Implement exporter-toolkit (closes #37)

### PR DESCRIPTION
**Pull request by DaAwesomeP**
This pull supersedes #37. This pull provides the following new features:

- TLS support
- Standard listening and logging options consistent with many other exporters
- Move to promlog to match many other exporters
- Supports listening on multiple ports simultaneously as well as Systemd socket listeners
- Prints and logs the exporter version and build information

The different command line options are breaking changes. This shift should make maintaining the exporter and bringing in future exporter-toolkit features (usually without further breaking changes) much easier.

I also updated many references to the previous repo that this repo superseded (that original repo is now archived).

I completely removed `-telemetry-listen-address` because...it didn't seem to do anything? It would log this port to the console, but unless there is a global variable being referenced somewhere it didn't actually listen on that port if it was different from `-modbus-listen-address`. The exporter-toolkit allows for listening on multiple ports at once which would effectively provide this functionality.

cc @bastischubert , @fschlich, and @SuperQ from the other pull, feel free to ignore if no longer relevant.

### CODE REVIEW

**Comment by SuperQ** [comment]
Nice. I think we should first drop the `vendor` dir. It's an old pattern we don't need anymore.

**Comment by SuperQ** [comment]
I opened https://github.com/RichiH/modbus_exporter/pull/43 as a cleanup step to make this PR easier.

**Comment by SuperQ** [comment]
@DaAwesomeP can you rebase this now that we've dropped the /vendor dir?

**Comment by DaAwesomeP** [comment]
> @DaAwesomeP can you rebase this now that we've dropped the /vendor dir?

@SuperQ working on this now!

**Comment by DaAwesomeP** [comment]
OK, I think this is good to go! Ready for review or merge.

**Review by SuperQ — APPROVED** [review]
Seems legit, we'll need to get some CI set up here.

**Comment by DaAwesomeP** [comment]
> Seems legit, we'll need to get some CI set up here.

Hah! Yes, I agree! I would really love the automatic tag/release artifact bit too.

**Pull request merged**
