### PR TITLE
Added ability to specify a directory of config files

### PR DESCRIPTION
**Pull request by omnistat**
After using this plugin for a little while, it started to become burdensome to navigate one huge configuration file for every metric of multiple modbus devices. I read through some issues and saw others mention this as well.

I decided to add basic functionality to specify either a single configuration file or a directory of configuration files in the format of [modbus.yml](https://github.com/omnistat/modbus_exporter/blob/main/modbus.yml). This will load all configurations as if they were in one file, but allows users to seperate them out for readability.

The folder name must end with `.d` to distinguish between a file or folder. For code simplicity, all files within the directory will attempt to be loaded, including non-yaml files, and error accordingly.

Example:
```python
modbus_configs.d
├── module1.yml
└── module2.yml

./modbus_exporter --config="modbus_configs.d"
```

Reflecting this change, the `--config.file` parameter has been changed to `--config` to be more general.

### CODE REVIEW

**Review by SuperQ — CHANGES_REQUESTED** [review]
This is not the way to handle this. Take a look how the multiple files/glob handling was done in the snmp_exporter.

https://github.com/prometheus/snmp_exporter/pull/970

**Comment by omnistat** [comment]
Thanks for the correction. I'll work on implementing this method instead. I wasn't aware this existed with the snmp exporter but I can see the rationale.

**Review by SuperQ — APPROVED** [review]
Nice, thanks!

**Comment by bastischubert** [comment]
@omnistat could you please update the readme.md that has a  conflict, so i can merge this pr ;)

**Comment by omnistat** [comment]
@bastischubert Done :)

**Pull request merged**
