### PR TITLE
Use promu build infra

### PR DESCRIPTION
**Pull request by SuperQ**
Use the Prometheus common makefile and promu for building.

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
@SuperQ Hah! You just beat me to my #47! Pick whichever you like more.

**Review by bastischubert — APPROVED** [review]
Lgtm

**Comment by DaAwesomeP** [comment]
@bastischubert May we consider #47 as well? If not that's fine and I'll close it, but merging this will make that very difficult to rebase. It covers more ground. I'm waiting on CircleCI to finish building and then I will mark it as ready for review.

**Comment by bastischubert** [comment]
@DaAwesomeP just reviewed this one and did not merge it as i already saw the #47 , which i'll have a look at in a few minutes

**Comment by SuperQ** [comment]
@DaAwesomeP you may want to include some of the Makefile changes I have here.

**Pull request closed without merging**
