### PR TITLE
✨ New easy-to-write register addresses

### LINKED ISSUE #22: ranges in 10,000 range now cause an error, rejects scraping
The support for large ranges 100,000 has broken the range checking 

```
time="2021-01-08T07:36:15Z" level=error msg="failed to scrape metrics for module 'sma_solar_inverter': metric: 'total_power_watts', address '30770': metric address should be within the range of 10000 - 40000.'1xxxx' for read coil / digital output, '2xxxx' for read discrete inputs / digital input,'3xxxx' read holding registers / analog output, '4xxxx' read input registers / analog input" source="modbus_exporter.go:148"
```

the register in the above example, `30773` is within the range supported. so the check is no longer valid. 

New change - https://github.com/RichiH/modbus_exporter/blob/master/modbus/modbus.go#L182
Previous commit  - https://github.com/RichiH/modbus_exporter/blob/master/modbus/modbus.go#L182

### PR DESCRIPTION
**Pull request by dshatohin**
New address format in `modbus.yml`:
- **first symbol** - modbus function code
- **all other symbols** - modbus register address

Backward compatibility included 🥳

Some tests are fixed (`modbus_test.go`)

Fixes #22

### CODE REVIEW

**Comment by RichiH** [comment]
Thanks! CC @bastischubert @rfc1036 for testing.

**Comment by bastischubert** [comment]
LGTM from a functional view.

When trying with an invalid address the error handling kicks in like this:

ERRO[0000] failed to scrape metrics for module 'SDC1-MM201-B03-F205-L1-current': metric 'current_amps', address '370004': modbus register address parcing failed  65535  source="modbus_exporter.go:148"

Before that commit, the error handling from modbus/modbus.go line 201ff kicked in with an error message, that is now no longer working. Maybe the whole error handling there (201-203) needs to be reviewed.

**Comment by RichiH** [comment]
Thanks @bastischubert. More descriptive and point-to-a-solution error messages would be good. I see @dshatohin is already taking a look, which is great.

**Comment by dshatohin** [comment]
Hi, thank you @RichiH and @bastischubert, I've just revisited error handling, now we are getting error for registers greater than 65535:
```
failed to scrape target '127.0.0.1:1502' with module 'fake': failed to scrape
metrics for module 'fake': modbus register address is out of range: 370004
```
and for wrong function code we are getting:
```
failed to scrape target '127.0.0.1:1502' with module 'fake': failed to scrape
metrics for module 'fake': metric: 'coil', address '560004': metric address should
be within the range of 10 - 465535.
'1xxxxx' for read coil / digital output,
'2xxxxx' for read discrete inputs / digital input,
'3xxxxx' read holding registers / analog output,
'4xxxxx' read input registers / analog input
```

**Comment by bastischubert** [comment]
LGTM @dshatohin

**Pull request merged**
