### PR TITLE
📖 Add ability to read Coils and DiscreteInputs

### PR DESCRIPTION
**Pull request by dshatohin**
#10 There was some problems with Coils and Discrete Inputs and I fixed it (at least I think so 😉)

### CODE REVIEW

**Comment by RichiH** [comment]
I currently don't have access to ModBus devices to test at the moment. @bastischubert, can you test this?

**Comment by dshatohin** [comment]
To be clear, I've compiled and tested it against real modbus TCP device and got my sweet ones and zeroes instead of error:
```
root@SHATOKHIN-WORK:modbus_exporter# curl "http://localhost:9602/metrics?module=real&sub_target=4&target=172.16.0.15:502"
# HELP coil1 some help for some coil
# TYPE coil1 gauge
coil1{module="real"} 0
# HELP coil2 some help for some coil
# TYPE coil2 gauge
coil2{module="real"} 1
# HELP di1 some help for some coil
# TYPE di1 gauge
di1{module="real"} 1
# HELP di2 some help for some coil
# TYPE di2 gauge
di2{module="real"} 1
```
In my understanding `binary.BigEndian.Uint16(rawData)` crashing after receiving `[]byte` with size 1.
So my solution is just converting first element of `[]byte` to `Uint16` like this `uint16(rawData[0])`.

**Comment by RichiH** [comment]
Let's give it a go, then :)

Thanks!

**Comment by rfc1036** [comment]
The test `TestParseModbusData` fails since this commit was merged.

```
go build
./modbus_exporter --help 2> help.txt || true
/home/md/go/bin/embedmd -w README.md
rm help.txt
go test ./...
ok  	github.com/lupoDharkael/modbus_exporter	(cached)
ok  	github.com/lupoDharkael/modbus_exporter/config	(cached)
--- FAIL: TestParseModbusData (0.01s)
    --- FAIL: TestParseModbusData/bool,_first_bit (0.00s)
        modbus_test.go:465: expected metric value to be 1 but got 0
    --- FAIL: TestParseModbusData/bool,_second_bit (0.00s)
        modbus_test.go:465: expected metric value to be 1 but got 0
FAIL
FAIL	github.com/lupoDharkael/modbus_exporter/modbus	0.013s
?   	github.com/lupoDharkael/modbus_exporter/tests/fake_server	[no test files]
FAIL
make: *** [Makefile:33: test] Errore 1
```

**Comment by dshatohin** [comment]
@rfc1036 Thank you for mentioning this!
As far as I can understand that tests - we are specifying `[]byte{uint8(0), uint8(2)}` but using only element number 0 in actual parsing function.
I think it is problem of tests, I'll check it later and fix it (if can be able to🤔)

**Pull request merged**
